### PR TITLE
Breaking: use `renderSubtreeIntoContainer` for passing context

### PR DESCRIPTION
**Pull request by vitorbal**
This PR simplifies the context implementation of `ElementPortal` to use `ReactDOM.unstable_renderSubtreeIntoContainer` instead of manually managing contexts.

This is a breaking change since the public API no longer named-exports `createElementPortal`.
If preferred, I could also modify the PR to be backwards-compatible by keeping the `createElementPortal` named-export for now.

### CODE REVIEW

**Comment by jdeal** [comment]
Thanks @vitorbal for the PR! This seems pretty solid to me. Do you want to go ahead and bump the version to 1.0.0? Then I'm okay dropping `createElementPortal` completely. I might also document a couple undocumented features on this branch before merging.

**Comment by vitorbal** [comment]
Sure! I was not sure if you'd like to bump the version yourself before making a new release, but I'll happily do it!


>  I might also document a couple undocumented features on this branch before merging.

I was actually planning on opening a separate PR for that too, haha 😄
If you'd like, I can cook something up later today if you don't get to it first :)

**Comment by vitorbal** [comment]
I've added a new commit that documents the `shouldReset` and `view` props, and the passing along of `data-` attributes. Let me know what you think!

**Comment by jdeal** [comment]
Perfect @vitorbal ! Thanks again!

**Pull request merged**
