### PR TITLE
Add new `withElementPortal` HOC (fixes #4)

### LINKED ISSUE #4: Proposal: add a `withElementPortal` Higher Order Component
It would be nice to export a [HOC](https://facebook.github.io/react/docs/higher-order-components.html) version of `ElementPortal` as well as the default Component version!

That would enable doing things like this:

```js
import { withElementPortal } from 'react-element-portal';
import { compose, connect } from 'react-redux';
import ReactDOM from 'react-dom';

const MyComponent = (props) => <h1>Hello, {props.name}!</h1>;

const MyComposedComponent = compose(
  withElementPortal(),
  connect((state) => ({ name: state.name }))
)(MyComponent);

// Somewhere in our app:
ReactDOM.render(
  <MyComponentWithPortal id="user" />,
  document.getElementById('app')
);
```

I have a suggested implementation ready here that includes tests and documentation: https://github.com/vitorbal/react-element-portal/commit/8bfddba9188a7e54b213f36e6c0b5bd1daf493d2

Let me know what you think of the idea :)

### PR DESCRIPTION
**Pull request by vitorbal**
Add a new `withElementPortal` HOC, as discussed in #4.

### CODE REVIEW

**Comment by jdeal** [comment]
Thanks again @vitorbal ! This looks ready to go. My only _mild_ concern is with the potential collision of props between the wrapped component and the portal. The most likely offender would be `id`. We _could_ change the prop names for the wrapped case. For example `portalId`, `portalSelector`, etc. Or we could consider switching to less ambiguous names for `ElementPortal` as well. I think for now, we should just roll with it like this, since I don't want to ugly things up without being sure. Just wanted to mention it though.

**Comment by vitorbal** [comment]
Thanks for the feedback, @jdeal! I totally agree with your concerns. I think prop collision is one of the biggest bummers of HOC's (one of the reasons a lot of folks prefer "function as child" components for many use cases).

IMO I'd favor switching the prop names of `ElementPortal` entirely in the future, instead of changing them *just* for the HOC, because I'm afraid the latter could add complexity to the component's API unnecessarily.

Agreed with keeping it as-is for now, though! 👍

**Comment by jdeal** [comment]
Merged! Thanks again.

**Comment by vitorbal** [comment]
No problem! Thanks for the feedback along the way :)

**Pull request merged**
